# Generated by Django 5.1.5 on 2026-03-15 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivedgroup',
            options={'verbose_name': 'Punkitga qabul (Guruh)', 'verbose_name_plural': 'Punkitga qabul'},
        ),
        migrations.AddField(
            model_name='arrivedgroup',
            name='delivered_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_groups', to=settings.AUTH_USER_MODEL, verbose_name='Topshirgan admin'),
        ),
        migrations.AddField(
            model_name='arrivedgroup',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Jami og'irlik (kg)"),
        ),
        migrations.AlterField(
            model_name='arrivedgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan admin'),
        ),
        migrations.AlterField(
            model_name='arrivedgroup',
            name='payment_status',
            field=models.CharField(choices=[("To'lov kutilmoqda", "To'lov kutilmoqda"), ('Tasdiqlash jarayonida', 'Tasdiqlash jarayonida'), ("To'lov tasdiqlandi", "To'lov tasdiqlandi"), ("To'lov rad etildi", "To'lov rad etildi"), ('Topshirildi', 'Topshirildi')], default="To'lov kutilmoqda", max_length=30),
        ),
    ]
