# Generated by Django 5.1.5 on 2026-03-12 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='arrived_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='warehouse.arrivedgroup', verbose_name='Kelganlar guruhi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cargos', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan admin"),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivered_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_actions', to=settings.AUTH_USER_MODEL, verbose_name='Topshirgan admin'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='onway_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onway_actions', to=settings.AUTH_USER_MODEL, verbose_name="Yo'lga chiqargan"),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cargos', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul admin"),
        ),
        migrations.AddField(
            model_name='cargo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_actions', to=settings.AUTH_USER_MODEL, verbose_name='Ombor admini'),
        ),
        migrations.CreateModel(
            name='ArrivedCargo',
            fields=[
            ],
            options={
                'verbose_name': 'Punkda (Topshirish)',
                'verbose_name_plural': 'Punktda (Topshirish)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='DeliveredCargo',
            fields=[
            ],
            options={
                'verbose_name': 'Topshirilgan yuk',
                'verbose_name_plural': 'Topshirilgan yuklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='OnWayCargo',
            fields=[
            ],
            options={
                'verbose_name': "Yo'ldagi yuk",
                'verbose_name_plural': "Yo'ldagi yuklar",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
        migrations.CreateModel(
            name='WarehouseCargo',
            fields=[
            ],
            options={
                'verbose_name': 'Ombordagi yuk',
                'verbose_name_plural': 'Ombordagi yuklar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cargo.cargo',),
        ),
    ]
